# -*- coding: utf-8 -*-
"""blinkit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z08niW7UffNTo8qTz_OLJPl3GxGmO7D3
"""

import pandas as pd
import numpy as np
orders = pd.read_csv('/blinkit_orders.csv')
order_items = pd.read_csv('/blinkit_order_items.csv')

orders.head(), order_items.head()

orders.info()
order_items.info()

orders.isnull().sum()
order_items.isnull().sum()

# Removing duplicate orders
orders = orders.drop_duplicates(subset='order_id')
# Convert order_date to datetime
orders['order_date'] = pd.to_datetime(orders['order_date'])
# Standardize order status text
orders['delivery_status'] = orders['delivery_status'].str.lower().str.strip()

# Remove duplicates
order_items = order_items.drop_duplicates()
# Remove invalid quantity or price
order_items = order_items[
    (order_items['quantity'] > 0) &
    (order_items['unit_price'] > 0)
]

order_items['item_total'] = (
    order_items['quantity'] * order_items['unit_price']
)

order_value = (
    order_items
    .groupby('order_id', as_index=False)
    .agg(
        total_items=('quantity', 'sum'),
        order_value=('item_total', 'sum')
    )
)

sales_data = pd.merge(
    orders,
    order_value,
    on='order_id',
    how='inner'
)
sales_data.head()
sales_data.info()

sales_data['order_value_bucket'] = pd.cut(
    sales_data['order_value'],
    bins=[0, 200, 500, 1000, np.inf],
    labels=['Low', 'Medium', 'High', 'Premium']
)

sales_data['order_day'] = sales_data['order_date'].dt.day_name()
sales_data['order_month'] = sales_data['order_date'].dt.month

sales_data.describe()
sales_data.isnull().sum()

sales_data.to_csv(
    'Sales_dataset_cleaned.csv',
    index=False
)

"""### **Customer Repeatation Analysis**"""

customers = pd.read_csv('/blinkit_customers.csv')
customers.head()

sales_data = pd.read_csv('/Sales_dataset_cleaned.csv')
cust_orders = pd.merge(
    sales_data,
    customers,
    on='customer_id',
    how='left'
)

customer_order_count = (
    cust_orders
    .groupby('customer_id', as_index=False)
    .agg(order_count=('order_id', 'count'))
)
customer_order_count['customer_type'] = customer_order_count['order_count'].apply(
    lambda x: 'Repeat' if x > 1 else 'New'
)

customer_clv = (
    cust_orders
    .groupby('customer_id', as_index=False)
    .agg(
        total_orders=('order_id', 'count'),
        clv=('order_total', 'sum'),
        avg_order_value=('order_total', 'mean')
    )
)

customer_clv['customer_type'] = customer_clv['total_orders'].apply(
    lambda x: 'Repeat' if x > 1 else 'New'
)

custom_repeat = customer_clv.copy()
custom_repeat.head()
custom_repeat.to_csv('custom_repeat.csv', index=False)

"""## Merging Products+Categories"""

import pandas as pd
products = pd.read_csv('/blinkit_products.csv')
order_items = pd.read_csv('/blinkit_order_items.csv')
products.info()

product_sales = pd.merge(
    order_items,
    products,
    on='product_id',
    how='left'
)

product_sales.head()
product_sales.isnull().sum()

product_sales['revenue'] = (
    product_sales['quantity'] * product_sales['unit_price']
)
product_sales['estimated_cost'] = (
    product_sales['revenue'] * (1 - product_sales['margin_percentage'] / 100)
)
product_sales['estimated_profit'] = (
    product_sales['revenue'] - product_sales['estimated_cost']
)

product_perf = (
    product_sales
    .groupby(
        ['product_id', 'product_name', 'category', 'brand'],
        as_index=False
    )
    .agg(
        units_sold=('quantity', 'sum'),
        total_revenue=('revenue', 'sum'),
        total_profit=('estimated_profit', 'sum'),
        avg_selling_price=('unit_price', 'mean')
    )
)

category_perf = (
    product_sales
    .groupby('category', as_index=False)
    .agg(
        total_units=('quantity', 'sum'),
        revenue=('revenue', 'sum'),
        profit=('estimated_profit', 'sum')
    )
)

category_perf['profit_margin_pct'] = (
    category_perf['profit'] / category_perf['revenue'] * 100
)

product_perf['discount_pct'] = (
    (products['mrp'] - products['price']) / products['mrp'] * 100
)

product_perf.to_csv('product_performance.csv', index=False)
category_perf.to_csv('category_performance.csv', index=False)

"""# Delivery Partner Performance"""

import pandas as pd
orders=pd.read_csv('/blinkit_orders.csv')
orders.columns

orders['promised_delivery_time'] = pd.to_datetime(orders['promised_delivery_time'])
orders['actual_delivery_time'] = pd.to_datetime(orders['actual_delivery_time'])

orders['delivery_delay_mins'] = (
    (orders['actual_delivery_time'] - orders['promised_delivery_time'])
    .dt.total_seconds() / 60
)

orders['on_time_flag'] = orders['delivery_delay_mins'].apply(
    lambda x: 1 if x <= 0 else 0
)

delivery_perf = (
    orders
    .groupby('delivery_partner_id', as_index=False)
    .agg(
        total_deliveries=('order_id', 'count'),
        on_time_deliveries=('on_time_flag', 'sum'),
        avg_delay_mins=('delivery_delay_mins', 'mean'),
        total_revenue=('order_total', 'sum')
    )
)

delivery_perf['on_time_pct'] = (
    delivery_perf['on_time_deliveries'] /
    delivery_perf['total_deliveries'] * 100
)

def delivery_rating(row):
    if row['on_time_pct'] >= 95 and row['avg_delay_mins'] <= 0:
        return 'Excellent'
    elif row['on_time_pct'] >= 85:
        return 'Good'
    elif row['on_time_pct'] >= 70:
        return 'Average'
    else:
        return 'Poor'
delivery_perf['performance_rating'] = delivery_perf.apply(
    delivery_rating, axis=1
)

delivery_perf.to_csv('delivery_partner_performance.csv', index=False)

"""## Customer Feedback(Sentiment Analysis)"""

import pandas as pd
feedback=pd.read_csv('/blinkit_customer_feedback.csv')
feedback.head()

import re
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text
feedback['clean_feedback'] = feedback['feedback_text'].apply(clean_text)

from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()
feedback['sentiment_score'] = feedback['clean_feedback'].apply(
    lambda x: sia.polarity_scores(x)['compound']
)
def sentiment_label(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'
feedback['sentiment'] = feedback['sentiment_score'].apply(sentiment_label)
feedback[['feedback_text', 'sentiment', 'sentiment_score']].head(20)

sentiment_summary = (
    feedback
    .groupby('sentiment', as_index=False)
    .agg(
        feedback_count=('feedback_text', 'count'),
        avg_rating=('rating', 'mean')
    )
)
sentiment_summary

orders = pd.read_csv('/blinkit_orders.csv')
orders.columns

orders['promised_delivery_time'] = pd.to_datetime(orders['promised_delivery_time'])
orders['actual_delivery_time'] = pd.to_datetime(orders['actual_delivery_time'])
orders['delivery_delay_mins'] = (
    (orders['actual_delivery_time'] - orders['promised_delivery_time'])
    .dt.total_seconds() / 60
)

orders[['order_id', 'delivery_delay_mins']].head()

feedback_orders = pd.merge(
    feedback,
    orders[['order_id', 'delivery_delay_mins', 'delivery_status']],
    on='order_id',
    how='left'
)

sentiment_delay = (
    feedback_orders
    .groupby('sentiment', as_index=False)
    .agg(
        avg_delay_mins=('delivery_delay_mins', 'mean'),
        feedback_count=('order_id', 'count')
    )
)
sentiment_delay

feedback_orders['on_time_flag'] = feedback_orders['delivery_delay_mins'].apply(
    lambda x: 1 if x <= 0 else 0
)
sentiment_ontime = (
    feedback_orders
    .groupby('sentiment', as_index=False)
    .agg(
        on_time_pct=('on_time_flag', 'mean')
    )
)
sentiment_ontime['on_time_pct'] *= 100
sentiment_ontime

feedback_orders.to_csv('feedback_delivery.csv', index=False)
sentiment_delay.to_csv('sentiment_delay_summary.csv', index=False)
sentiment_ontime.to_csv('sentiment_ontime_summary.csv', index=False)